### ISSUE TITLE
6.6.2 Enhanced Statistics uses LinkSet wrongly

### ISSUE THREAD

**Issue by VladimirAlexiev** [joejimbo/HCLSDatasetDescriptions#81]
Sec 6.6.2 uses LinkSet to provide
- properties and the number of unique objects linked to the property
- properties and the number of unique literals

This is totally wrong: void:LinkSet and void:linkPredicate are used to describe links between datasets, not counts within one dataset.
You should use void:propertyPartition (and maybe void:classPartition within it) and void:distinctSubjects.

**Comment by micheldumontier** [comment]
@VladimirAlexiev can you have another look at the latest?

**Comment by micheldumontier** [comment]
refactored statistics have now been merged as per commit e85578a9da34c2022b971141dcdb386437d3d7a4
