### ISSUE TITLE
idot:accessPattern in summary level?

### ISSUE THREAD

**Issue by agbeltran** [joejimbo/HCLSDatasetDescriptions#98]
idot:accessPattern appears as MAY/MAY/MAY for summary/version/distribution levels.
Then, in the explanatory text, it reads:
"The idot:accessPattern MAY be used to specify how to access specific formats of the resources. "

So, as it is referring to formats, I was wondering if this property should be at the summary level at all, as it seems it only makes sense at version/distribution level? Actually, maybe only distribution level?

In the chembl example, it is used at the summary level too. 

Thanks!

**Comment by micheldumontier** [comment]
I believe it is appropriate to have it at each level. at the summary level, it would be an access pattern that is independent of version or format. at the version level the access pattern should specify a way to get back a specific version, and at the distribution level, we should be able to get version and/or format retrieval.

**Comment by micheldumontier** [comment]
However, it does make sense that we restrict this access information to only the distribution level.

**Comment by micheldumontier** [comment]
During our discussion in today's call we resolved that:
1. accessPattern has a value of idot:AccessPattern
2. accessPattern must not be used in summary and version levels, and may be used at the distribution level.
